import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, join } from "node:path";

import type { HostWrapperShellInstallResult, HostWrapperShellInvocation } from "./types.js";

const SHELL_WRAPPER_START_MARKER = "# >>> oraculum host wrapper >>>";
const SHELL_WRAPPER_END_MARKER = "# <<< oraculum host wrapper <<<";

export function getHostWrapperSnippetPath(
  homeDir = homedir(),
  shellPath = process.env.SHELL,
): string {
  const shellName = basename(shellPath ?? "zsh");
  const extension = shellName === "bash" ? "bash" : "zsh";
  return join(homeDir, ".oraculum", "chat-native", "shell", `oraculum-host-wrapper.${extension}`);
}

export function resolveHostWrapperRcPath(
  homeDir = homedir(),
  shellPath = process.env.SHELL,
): string | undefined {
  const shellName = basename(shellPath ?? "zsh");
  if (shellName === "bash") {
    return join(homeDir, ".bashrc");
  }

  if (shellName === "zsh") {
    return join(homeDir, ".zshrc");
  }

  return undefined;
}

export function buildHostWrapperShellSnippet(
  snippetPath: string,
  invocation?: HostWrapperShellInvocation,
): string {
  const cliCommand = invocation
    ? [shellQuote(invocation.command), ...invocation.args.map(shellQuote)].join(" ")
    : "oraculum";
  const invocationGuard = invocation
    ? `[ -x ${shellQuote(invocation.command)} ]`
    : "command -v oraculum >/dev/null 2>&1";
  return [
    "# Generated by Oraculum. Source from your shell rc to keep `codex` and `claude` UX unchanged",
    "# while filtering host-owned `orc ...` wrapper noise.",
    `if [ -n "\${ORACULUM_DISABLE_HOST_WRAPPER:-}" ]; then`,
    "  return 0",
    "fi",
    "",
    `if ! ${invocationGuard}; then`,
    "  return 0",
    "fi",
    "",
    `ORACULUM_REAL_CODEX_BINARY="\${ORACULUM_REAL_CODEX_BINARY:-$(command -v codex 2>/dev/null)}"`,
    `ORACULUM_REAL_CLAUDE_BINARY="\${ORACULUM_REAL_CLAUDE_BINARY:-$(command -v claude 2>/dev/null)}"`,
    "",
    "codex() {",
    '  ORACULUM_HOST_WRAPPER_REAL_BINARY="$ORACULUM_REAL_CODEX_BINARY" command ' +
      `${cliCommand} host-wrapper codex -- "$@"`,
    "}",
    "",
    "claude() {",
    '  ORACULUM_HOST_WRAPPER_REAL_BINARY="$ORACULUM_REAL_CLAUDE_BINARY" command ' +
      `${cliCommand} host-wrapper claude-code -- "$@"`,
    "}",
    "",
    `# Source marker path: ${snippetPath}`,
    "",
  ].join("\n");
}

export async function installHostWrapperShellBindings(options?: {
  homeDir?: string;
  invocation?: HostWrapperShellInvocation;
  shellPath?: string;
}): Promise<HostWrapperShellInstallResult> {
  const homeDir = options?.homeDir ?? homedir();
  const shellPath = options?.shellPath ?? process.env.SHELL;
  const snippetPath = getHostWrapperSnippetPath(homeDir, shellPath);
  const rcPath = resolveHostWrapperRcPath(homeDir, shellPath);

  await mkdir(dirname(snippetPath), { recursive: true });
  await writeFile(
    snippetPath,
    `${buildHostWrapperShellSnippet(snippetPath, options?.invocation)}\n`,
    "utf8",
  );

  if (!rcPath) {
    return { snippetPath };
  }

  const sourceBlock = [
    SHELL_WRAPPER_START_MARKER,
    `[ -f "${snippetPath}" ] && source "${snippetPath}"`,
    SHELL_WRAPPER_END_MARKER,
  ].join("\n");

  const existing = existsSync(rcPath) ? await readFile(rcPath, "utf8") : "";
  const next = stripHostWrapperSourceBlock(existing);
  const separator = next.length > 0 && !next.endsWith("\n") ? "\n\n" : next.length > 0 ? "\n" : "";
  await writeFile(rcPath, `${next}${separator}${sourceBlock}\n`, "utf8");

  return { snippetPath, rcPath };
}

export async function uninstallHostWrapperShellBindings(options?: {
  homeDir?: string;
  shellPath?: string;
}): Promise<void> {
  const homeDir = options?.homeDir ?? homedir();
  const shellPath = options?.shellPath ?? process.env.SHELL;
  const snippetPath = getHostWrapperSnippetPath(homeDir, shellPath);
  const rcPath = resolveHostWrapperRcPath(homeDir, shellPath);

  if (rcPath && existsSync(rcPath)) {
    const existing = await readFile(rcPath, "utf8");
    await writeFile(
      rcPath,
      `${stripHostWrapperSourceBlock(existing).replace(/\s+$/u, "")}\n`,
      "utf8",
    );
  }

  await rm(snippetPath, { force: true, recursive: true });
}

export function stripHostWrapperSourceBlock(value: string): string {
  const pattern = new RegExp(
    `${escapeRegExp(SHELL_WRAPPER_START_MARKER)}[\\s\\S]*?${escapeRegExp(SHELL_WRAPPER_END_MARKER)}\\n?`,
    "gu",
  );
  return value.replace(pattern, "").replace(/\n{3,}/gu, "\n\n");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/gu, `'\\''`)}'`;
}
