export function buildFakeCodexSource(planLiftHarness) {
  const promptMarkers = JSON.stringify(planLiftHarness.planLiftPromptMarkers);
  return [
    "const fs = require('node:fs');",
    "const path = require('node:path');",
    `const promptMarkers = ${promptMarkers};`,
    "const prompt = fs.readFileSync(0, 'utf8');",
    "const args = process.argv.slice(2);",
    "const outIndex = args.indexOf('-o');",
    "const outPath = outIndex >= 0 ? args[outIndex + 1] || '' : '';",
    "const candidateMatch = prompt.match(/^Candidate ID: (.+)$/m);",
    "const candidateId = candidateMatch ? candidateMatch[1].trim() : 'cand-01';",
    "const isPreflight = prompt.includes(promptMarkers.preflight);",
    "const isProfileSelection = promptMarkers.profileFields.every((field) => prompt.includes(field));",
    "const isWinner = prompt.includes(promptMarkers.winner);",
    "function respond(payload) {",
    "  const text = typeof payload === 'string' ? payload : JSON.stringify(payload);",
    "  if (outPath) fs.writeFileSync(outPath, text, 'utf8');",
    "  process.stdout.write(text + '\\\\n');",
    "}",
    "function resolveCandidateWorkspaceRoot() {",
    "  const cwd = process.cwd();",
    "  const workspaceMarker = path.sep + '.oraculum' + path.sep + 'workspaces' + path.sep;",
    "  if (cwd.includes(workspaceMarker)) return cwd;",
    "  if (!outPath) return cwd;",
    "  const segments = outPath.split(path.sep);",
    "  const dotOraculumIndex = segments.lastIndexOf('.oraculum');",
    "  const candidatesIndex = segments.lastIndexOf('candidates');",
    "  if (dotOraculumIndex < 0 || candidatesIndex < 0) return cwd;",
    "  const rootSegments = segments.slice(0, dotOraculumIndex);",
    "  const runId = segments[dotOraculumIndex + 2] || '';",
    "  const candidateIdFromPath = segments[candidatesIndex + 1] || candidateId;",
    "  const workspaceBase =",
    "    rootSegments[0] === ''",
    "      ? path.join(path.sep, ...rootSegments.slice(1))",
    "      : path.join(...rootSegments);",
    "  return path.join(workspaceBase, '.oraculum', 'workspaces', runId, candidateIdFromPath);",
    "}",
    "function resolveProjectRoot() {",
    "  const cwd = process.cwd();",
    "  const workspaceMarker = path.sep + '.oraculum' + path.sep + 'workspaces' + path.sep;",
    "  if (cwd.includes(workspaceMarker) && outPath) {",
    "    const segments = outPath.split(path.sep);",
    "    const dotOraculumIndex = segments.lastIndexOf('.oraculum');",
    "    if (dotOraculumIndex >= 0) {",
    "      const rootSegments = segments.slice(0, dotOraculumIndex);",
    "      return rootSegments[0] === ''",
    "        ? path.join(path.sep, ...rootSegments.slice(1))",
    "        : path.join(...rootSegments);",
    "    }",
    "  }",
    "  return cwd.includes(workspaceMarker)",
    "    ? cwd.slice(0, cwd.indexOf(workspaceMarker))",
    "    : cwd;",
    "}",
    "function resolveScenarioId() {",
    "  const projectRoot = resolveProjectRoot();",
    "  const markerPath = path.join(projectRoot, '.oraculum', 'plan-lift-scenario.txt');",
    "  if (!fs.existsSync(markerPath)) return '';",
    "  return fs.readFileSync(markerPath, 'utf8').trim();",
    "}",
    "const scenarioId = resolveScenarioId();",
    "function write(relativePath, contents) {",
    "  const workspaceRoot = resolveCandidateWorkspaceRoot();",
    "  const absolutePath = path.join(workspaceRoot, relativePath);",
    "  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });",
    "  fs.writeFileSync(absolutePath, contents, 'utf8');",
    "}",
    "if (isPreflight) {",
    "  respond({ decision: 'proceed', confidence: 'high', summary: 'The task contract is explicit enough to proceed.', researchPosture: 'repo-only' });",
    "  process.exit(0);",
    "}",
    "if (isProfileSelection) {",
    "  respond({",
    "    validationProfileId: 'generic',",
    "    confidence: 'high',",
    "    validationSummary: 'Use the default generic validation profile for the fixture.',",
    "    candidateCount: 2,",
    "    strategyIds: ['minimal-change', 'safety-first'],",
    "    selectedCommandIds: [],",
    "    validationGaps: [],",
    "  });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('selecting the planning depth')) {",
    "  respond({ depth: 'skip-interview', readiness: 'ready', confidence: 'high', summary: 'The plan-lift fixture task is explicit enough to plan.', reasons: ['Fixture task packet is pre-authored.'], estimatedInterviewRounds: 0, consensusReviewDepth: 'standard' });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('deciding whether the new `orc plan` input answers')) {",
    "  respond({ classification: 'new-task', confidence: 'high', summary: 'Plan-lift fixtures do not use interview continuations.' });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('asking the next planning interview question')) {",
    "  respond({ question: 'What concrete result should this fixture preserve?', perspective: 'fixture-contract' });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('scoring whether the latest planning interview answer')) {",
    "  respond({ clarityScore: 1, weakestDimension: 'none', readyForSpec: true, assumptions: [], ontologySnapshot: { goals: [], constraints: [], nonGoals: [], acceptanceCriteria: [], risks: [] } });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('crystallizing an explicit Oraculum planning interview')) {",
    "  respond({ goal: 'Preserve the plan-lift fixture task contract.', constraints: [], nonGoals: [], acceptanceCriteria: ['Use the fixture task packet and generated consultation plan.'], assumptionsResolved: [], assumptionLedger: [], repoEvidence: ['Plan-lift fixture task packet.'], openRisks: [] });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('drafting a consensus-reviewed Oraculum consultation plan')) {",
    "  respond('plan-lift consensus draft unavailable; use fallback draft');",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('architect reviewer') || prompt.includes('critic reviewer')) {",
    "  respond({ verdict: 'approve', summary: 'Plan-lift fallback draft is acceptable.', requiredChanges: [], tradeoffs: [], risks: [] });",
    "  process.exit(0);",
    "}",
    "if (prompt.includes('revising a consensus consultation plan draft')) {",
    "  respond('plan-lift consensus revision unavailable; keep existing draft');",
    "  process.exit(0);",
    "}",
    "if (isWinner) {",
    "  const planned = prompt.includes('Planned judging criteria:');",
    "  if (scenarioId === 'multi-artifact-contract-coverage') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated both contract artifacts coherently.' : 'cand-01 satisfied the primary artifact with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both docs/PRD.md and docs/ACCEPTANCE.md coherently.'] : ['Prioritize the primary artifact when both finalists remain reviewable.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'forbidden-collateral-boundary') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 preserved the collateral boundary while improving the PRD.' : 'cand-01 leaves the broader visible update set.', judgingCriteria: planned ? ['Prefer finalists that improve docs/PRD.md without mutating docs/CHANGELOG.md.'] : ['Prefer the finalist with the broader visible PRD-related diff.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'workstream-dependency-discipline') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 grounded the rollout in the canonical PRD before expanding rollout steps.' : 'cand-01 updates the rollout artifact with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update docs/PRD.md before or alongside docs/ROLLOUT.md.'] : ['Prefer the finalist that most directly updates the rollout artifact.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'specificity-reviewability-bias') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable specification bundle.' : 'cand-01 keeps both files aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make both docs/PRD.md and docs/ACCEPTANCE.md concrete and operator-reviewable.'] : ['Prefer the finalist that keeps both files aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'multi-stage-sequenced-coverage') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 closed the PRD, API, and checklist stages as one reviewable bundle.' : 'cand-01 closes the first staged contract with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that close docs/PRD.md, docs/API.md, and docs/CHECKLIST.md as one staged bundle.'] : ['Prefer the finalist that most directly updates the API contract.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'placeholder-crown-gate-bias') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 resolves the PRD and risk bundle without placeholders.' : 'cand-01 keeps both files aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that resolve both docs/PRD.md and docs/RISKS.md concretely without TODO placeholders.'] : ['Prefer the finalist that keeps the written bundle compact.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'fallback-policy-stage-guard') {",
    "    process.stderr.write('winner unavailable for fallback evidence\\\\n');",
    "    process.exit(1);",
    "  }",
    "  if (scenarioId === 'package-script-fallback-stage-guard') {",
    "    process.stderr.write('winner unavailable for fallback evidence\\\\n');",
    "    process.exit(1);",
    "  }",
    "  if (scenarioId === 'code-config-contract-coverage') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated the Python implementation and paired runtime config coherently.' : 'cand-01 changed the implementation with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both src/session.py and config/session.yaml coherently.'] : ['Prioritize the implementation artifact when both finalists remain reviewable.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'code-config-reviewability-bias') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable runtime bundle.' : 'cand-01 keeps the runtime bundle aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make src/session.py and config/session.yaml concrete and operator-reviewable.'] : ['Prefer the finalist that keeps the runtime bundle aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'polyglot-contract-coverage') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated the Python runtime and Go status artifacts coherently.' : 'cand-01 changed the Python runtime with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both services/api/app.py and internal/status/status.go coherently.'] : ['Prioritize the Python runtime artifact when both finalists remain reviewable.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'polyglot-reviewability-bias') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable cross-language runtime bundle.' : 'cand-01 keeps the cross-language bundle aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make services/api/app.py and internal/status/status.go concrete and operator-reviewable.'] : ['Prefer the finalist that keeps the cross-language bundle aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'python-rust-contract-coverage') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated the Python runtime and Rust core artifacts coherently.' : 'cand-01 changed the Python runtime with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both services/session/restore.py and crates/session_core/src/lib.rs coherently.'] : ['Prioritize the Python runtime artifact when both finalists remain reviewable.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'package-oracle-code-test-contract') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated the runtime implementation and regression bundle while keeping the package oracle green.' : 'cand-01 changed the implementation with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both packages/auth/src/session.ts and packages/auth/test/session-refresh.test.ts while preserving the package-local runtime oracle.'] : ['Prioritize the implementation artifact when both finalists keep the package runtime valid.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'project-oracle-api-schema-reviewability') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable handler and schema bundle while preserving the project API oracle.' : 'cand-01 keeps the handler and schema bundle aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make services/http/session_handler.py and api/openapi/session.yaml concrete and operator-reviewable while preserving the project API oracle.'] : ['Prefer the finalist that keeps the API bundle aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'workspace-oracle-package-config-contract') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated the billing runtime and package config bundle while keeping the workspace oracle green.' : 'cand-01 changed the billing runtime with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both packages/billing/src/reconcile.ts and packages/billing/config/reconcile.json while preserving the workspace-scoped billing runtime oracle.'] : ['Prioritize the billing runtime artifact when both finalists keep the package oracle valid.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'workspace-oracle-package-config-reviewability') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable billing runtime bundle while preserving the workspace oracle.' : 'cand-01 keeps the billing package bundle aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make packages/billing/src/reconcile.ts and packages/billing/config/reconcile.json concrete and operator-reviewable while preserving the workspace-scoped billing runtime oracle.'] : ['Prefer the finalist that keeps the billing package bundle aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'dual-oracle-migration-rollback-reviewability') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete migration, rollback, and runtime bundle while preserving both repo-local oracles.' : 'cand-01 keeps the migration bundle aligned with the most compact visible rewrite that still passes the oracles.', judgingCriteria: planned ? ['Prefer finalists that make packages/payments/src/migration.ts, db/migrations/20260416_add_session_restore.sql, and docs/ROLLBACK.md concrete and operator-reviewable while preserving both repo-local oracles.'] : ['Prefer the finalist that keeps the migration bundle aligned with the leanest visible rewrite while the oracles stay green.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'package-script-project-oracle-reviewability') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete release bundle while preserving the workspace package script and project rollback oracles.' : 'cand-01 keeps the release bundle aligned with the most compact visible rewrite that still passes both oracles.', judgingCriteria: planned ? ['Prefer finalists that make packages/web/src/session.ts, db/migrations/20260416_release_session_restore.sql, and docs/ROLLBACK.md concrete and operator-reviewable while preserving both repo-local oracles.'] : ['Prefer the finalist that keeps the release bundle aligned with the leanest visible rewrite while both oracles stay green.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'package-script-repair-stage-guard') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 closes the staged release bundle instead of relying only on repaired review evidence.' : 'cand-01 repaired the missing review note with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that finish docs/VERIFY.md and the staged release bundle instead of relying only on repair output.'] : ['Prefer the finalist that recovered review evidence with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'code-test-contract-coverage') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 updated the implementation and paired regression test coherently.' : 'cand-01 changed the implementation with the leanest visible diff.', judgingCriteria: planned ? ['Prefer finalists that update both packages/auth/src/session.ts and packages/auth/test/session-refresh.test.ts coherently.'] : ['Prioritize the implementation artifact when both finalists remain reviewable.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'api-schema-reviewability-bias') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable handler and schema bundle.' : 'cand-01 keeps the API bundle aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make services/http/session_handler.py and api/openapi/session.yaml concrete and operator-reviewable.'] : ['Prefer the finalist that keeps the API bundle aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "  if (scenarioId === 'rust-config-reviewability-bias') {",
    "    respond({ decision: 'select', candidateId: planned ? 'cand-02' : 'cand-01', confidence: 'high', summary: planned ? 'cand-02 leaves a concrete, operator-reviewable Rust runtime bundle.' : 'cand-01 keeps the Rust runtime bundle aligned with the most compact visible rewrite.', judgingCriteria: planned ? ['Prefer finalists that make crates/session_core/src/lib.rs and deploy/session-policy.yaml concrete and operator-reviewable.'] : ['Prefer the finalist that keeps the Rust runtime bundle aligned with the leanest visible rewrite.'] });",
    "    process.exit(0);",
    "  }",
    "}",
    "if (scenarioId === 'multi-artifact-contract-coverage') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the session.',''].join('\\\\n'));",
    "    respond('Updated only the primary PRD contract.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the session.',''].join('\\\\n'));",
    "  write('docs/ACCEPTANCE.md', ['# Acceptance','- Refresh preserves the authenticated session.','- Logging out still clears the session on the next load.',''].join('\\\\n'));",
    "  respond('Updated both planned contract artifacts.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'forbidden-collateral-boundary') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/PRD.md', ['# Goal','Preserve the authenticated session across refresh.','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the session.',''].join('\\\\n'));",
    "    write('docs/CHANGELOG.md', '# Changelog\\\\n\\\\nUpdated during PRD rewrite.\\\\n');",
    "    respond('Updated the PRD but also drifted into the changelog.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','Preserve the authenticated session across a normal browser refresh so signed-in users stay signed in.','','# Constraints','- Keep the current login and logout user experience unchanged.','- Do not broaden scope beyond refresh-time session persistence.','','# Acceptance Criteria','- Refreshing the page preserves the authenticated session.','- Logging out still clears the session on the next page load.',''].join('\\\\n'));",
    "  respond('Specific PRD rewrite without collateral drift.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'workstream-dependency-discipline') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/ROLLOUT.md', ['# Rollout','- Rollout preserves the session contract during refresh.','- Verify the rollout during review.',''].join('\\\\n'));",
    "    respond('Updated only the rollout artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the session contract.',''].join('\\\\n'));",
    "  write('docs/ROLLOUT.md', ['# Rollout','- Rollout preserves the session contract during a normal browser refresh.','- Roll out only after the canonical PRD is accepted.',''].join('\\\\n'));",
    "  respond('Updated the canonical PRD and the rollout artifact together.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'specificity-reviewability-bias') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/PRD.md', ['# Goal','Improve session reliability.','','# Constraints','- Keep the current experience stable.','','# Acceptance Criteria','- Add checks later.',''].join('\\\\n'));",
    "    write('docs/ACCEPTANCE.md', ['# Acceptance','- Improve reliability.','- Add more checks when ready.',''].join('\\\\n'));",
    "    respond('Updated both specification artifacts with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','Preserve the authenticated session across a normal browser refresh so signed-in users stay signed in.','','# Constraints','- Keep the current login and logout user experience unchanged.','- Logging out must still clear the session on the next page load.','','# Acceptance Criteria','- Refreshing the page preserves the authenticated session.','- Logging out clears the session on the next page load.',''].join('\\\\n'));",
    "  write('docs/ACCEPTANCE.md', ['# Acceptance','- Refresh preserves the authenticated session.','- Logging out clears the session on the next page load.','- Reviewers can verify both checks from the written contract alone.',''].join('\\\\n'));",
    "  respond('Updated both specification artifacts with concrete reviewable language.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'multi-stage-sequenced-coverage') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the canonical contract.',''].join('\\\\n'));",
    "    write('docs/API.md', ['# API','- session restore API contract','- Return the existing session after a normal browser refresh.',''].join('\\\\n'));",
    "    respond('Closed the first staged contract but left the checklist stale.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the canonical contract.',''].join('\\\\n'));",
    "  write('docs/API.md', ['# API','- session restore API contract','- Return the existing session after a normal browser refresh.',''].join('\\\\n'));",
    "  write('docs/CHECKLIST.md', ['# Checklist','- Operators can verify the staged bundle.','- Review PRD, API, and checklist changes together before approval.',''].join('\\\\n'));",
    "  respond('Closed the full staged bundle, including the final checklist stage.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'placeholder-crown-gate-bias') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/PRD.md', ['# Goal','Improve session restore behavior.','','# Constraints','- Keep the user experience stable.','','# Acceptance Criteria','- TODO decide later.',''].join('\\\\n'));",
    "    write('docs/RISKS.md', ['# Risks','- TODO choose the rollback path later.','- Review mitigation after implementation.',''].join('\\\\n'));",
    "    respond('Updated both files with a compact but unresolved placeholder bundle.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','Preserve the authenticated session across a normal browser refresh so signed-in users stay signed in.','','# Constraints','- Keep the current login and logout user experience unchanged.','- Logging out must still clear the session on the next page load.','','# Acceptance Criteria','- Refreshing the page preserves the authenticated session.','- Logging out clears the session on the next page load.',''].join('\\\\n'));",
    "  write('docs/RISKS.md', ['# Risks','- If session restore misbehaves, disable the session restore flag and fall back to the existing login flow.','- Reviewers can approve the mitigation without adding follow-up placeholders.',''].join('\\\\n'));",
    "  respond('Updated both files with a resolved, reviewable bundle.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'fallback-policy-stage-guard') {",
    "  if (candidateId === 'cand-01') {",
    "    write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the canonical contract.',''].join('\\\\n'));",
    "    write('docs/OPS.md', ['# Ops','- session restore operations contract','- Restore the existing session after a normal browser refresh.',''].join('\\\\n'));",
    "    respond('Closed the first staged operations contract only.');",
    "    process.exit(0);",
    "  }",
    "  write('docs/PRD.md', ['# Goal','canonical session contract','','# Constraints','- Keep logout behavior unchanged.','','# Acceptance Criteria','- Refresh preserves the canonical contract.',''].join('\\\\n'));",
    "  write('docs/OPS.md', ['# Ops','- session restore operations contract','- Restore the existing session after a normal browser refresh.',''].join('\\\\n'));",
    "  write('docs/VERIFY.md', ['# Verify','- Operators can verify the fallback-safe staged bundle.','- Review PRD, ops, and verification notes together before approval.',''].join('\\\\n'));",
    "  respond('Closed the staged operations bundle so fallback can safely select the survivor.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'package-script-fallback-stage-guard') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/web/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  return existingSession;','}',''].join('\\\\n'));",
    "    write('db/migrations/20260416_release_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT DEFAULT \\'existing-session\\';','UPDATE sessions SET restore_mode = \\'existing-session\\' WHERE restore_mode IS NULL;',''].join('\\\\n'));",
    "    write('docs/ROLLBACK.md', ['# Rollback','- Disable the session-restore release flag before rollback.','- ALTER TABLE sessions DROP COLUMN restore_mode;',''].join('\\\\n'));",
    "    respond('Closed the release contract stage only; verification stayed stale.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/web/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "  write('db/migrations/20260416_release_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT DEFAULT \\'existing-session\\';','UPDATE sessions SET restore_mode = \\'existing-session\\' WHERE restore_mode IS NULL;',''].join('\\\\n'));",
    "  write('docs/ROLLBACK.md', ['# Rollback','- Disable the session-restore release flag before rollback.','- ALTER TABLE sessions DROP COLUMN restore_mode;','- Re-run the workspace session test after rollback.',''].join('\\\\n'));",
    "  write('docs/VERIFY.md', ['# Verify','- Operators can verify the fallback-safe release bundle.','- Review runtime, migration, rollback, and verification notes together before approval.',''].join('\\\\n'));",
    "  respond('Closed the full staged release bundle so fallback can safely select the survivor.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'code-config-contract-coverage') {",
    "  if (candidateId === 'cand-01') {",
    "    write('src/session.py', ['def restore_session(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "    respond('Updated only the Python implementation artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('src/session.py', ['def restore_session(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "  write('config/session.yaml', ['restore_on_refresh: true','logout_clears_on_next_load: true',''].join('\\\\n'));",
    "  respond('Updated the Python implementation and paired runtime config.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'code-config-reviewability-bias') {",
    "  if (candidateId === 'cand-01') {",
    "    write('src/session.py', ['def restore_session(request):','    # Improve reliability later.','    return request.session',''].join('\\\\n'));",
    "    write('config/session.yaml', ['restore_on_refresh: later','logout_clears_on_next_load: review-later',''].join('\\\\n'));",
    "    respond('Updated the code and config bundle with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('src/session.py', ['def restore_session(request):','    \"\"\"Preserve the authenticated session across a normal browser refresh.\"\"\"','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "  write('config/session.yaml', ['restore_on_refresh: true','logout_clears_on_next_load: true',''].join('\\\\n'));",
    "  respond('Updated the code and config bundle with concrete runtime markers.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'polyglot-contract-coverage') {",
    "  if (candidateId === 'cand-01') {",
    "    write('services/api/app.py', ['def restore_session(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "    respond('Updated only the Python runtime artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('services/api/app.py', ['def restore_session(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "  write('internal/status/status.go', ['package status','','const SessionRestoreStatus = \"SessionRestored\"',''].join('\\\\n'));",
    "  respond('Updated the Python runtime and paired Go status artifact.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'polyglot-reviewability-bias') {",
    "  if (candidateId === 'cand-01') {",
    "    write('services/api/app.py', ['def restore_session(request):','    # Improve cross-language behavior steadily.','    return request.session',''].join('\\\\n'));",
    "    write('internal/status/status.go', ['package status','','const SessionRestoreStatus = \"SessionReady\"',''].join('\\\\n'));",
    "    respond('Updated the Python and Go bundle with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('services/api/app.py', ['def restore_session(request):','    \"\"\"Preserve the authenticated session across a normal browser refresh.\"\"\"','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "  write('internal/status/status.go', ['package status','','const SessionRestoreStatus = \"SessionRestored\"','const LogoutStatus = \"LogoutClearsOnNextLoad\"',''].join('\\\\n'));",
    "  respond('Updated the Python and Go bundle with concrete cross-language runtime markers.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'python-rust-contract-coverage') {",
    "  if (candidateId === 'cand-01') {",
    "    write('services/session/restore.py', ['def restore_session(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "    respond('Updated only the Python runtime artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('services/session/restore.py', ['def restore_session(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return existing_session',''].join('\\\\n'));",
    "  write('crates/session_core/src/lib.rs', ['pub const SESSION_RESTORE_MODE: &str = \"existing-session\";',''].join('\\\\n'));",
    "  respond('Updated the Python runtime and paired Rust core artifact.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'package-oracle-code-test-contract') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/auth/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "    respond('Updated only the package runtime implementation artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/auth/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "  write('packages/auth/test/session-refresh.test.ts', ['import { expect, test } from \"vitest\";','import { restoreSession } from \"../src/session\";','','test(\"restoreSession keeps the signed-in user across refresh\", () => {','  const existingSession = { userId: \"user-123\" };','  const request = { session: existingSession };','  expect(restoreSession(request)).toEqual(existingSession);','});',''].join('\\\\n'));",
    "  respond('Updated the package runtime implementation and paired regression test artifact.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'project-oracle-api-schema-reviewability') {",
    "  if (candidateId === 'cand-01') {",
    "    write('services/http/session_handler.py', ['def build_session_response(request):','    return {\"status\": \"ready\"}',''].join('\\\\n'));",
    "    write('api/openapi/session.yaml', ['status: ready','logout_behavior: review-later',''].join('\\\\n'));",
    "    respond('Updated the handler and schema bundle with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('services/http/session_handler.py', ['def build_session_response(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return {\"status\": \"restored\", \"logout_behavior\": \"clears-on-next-load\"}',''].join('\\\\n'));",
    "  write('api/openapi/session.yaml', ['status: restored','logout_behavior: clears-on-next-load','review_notes: concrete-and-ready',''].join('\\\\n'));",
    "  respond('Updated the handler and schema bundle with a concrete, operator-reviewable API contract.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'workspace-oracle-package-config-contract') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/billing/src/reconcile.ts', ['export function reconcileRestore(request) {','  const existingSession = request.session;','  return existingSession;','}',''].join('\\\\n'));",
    "    respond('Updated only the billing package runtime artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/billing/src/reconcile.ts', ['export function reconcileRestore(request) {','  const existingSession = request.session;','  return existingSession;','}',''].join('\\\\n'));",
    "  write('packages/billing/config/reconcile.json', ['{','  \"restoreMode\": \"existing-session\",','  \"logoutBehavior\": \"clears-on-next-load\"','}',''].join('\\\\n'));",
    "  respond('Updated the billing package runtime and paired config artifact.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'workspace-oracle-package-config-reviewability') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/billing/src/reconcile.ts', ['export function reconcileRestore(request) {','  const existingSession = request.session;','  return existingSession;','}',''].join('\\\\n'));",
    "    write('packages/billing/config/reconcile.json', ['{','  \"restoreMode\": \"steady-improvement\",','  \"logoutBehavior\": \"review-later\"','}',''].join('\\\\n'));",
    "    respond('Updated the billing package bundle with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/billing/src/reconcile.ts', ['export function reconcileRestore(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "  write('packages/billing/config/reconcile.json', ['{','  \"restoreMode\": \"existing-session\",','  \"logoutBehavior\": \"clears-on-next-load\"','}',''].join('\\\\n'));",
    "  respond('Updated the billing package bundle with a concrete, operator-reviewable runtime contract.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'dual-oracle-migration-rollback-reviewability') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/payments/src/migration.ts', ['export function currentRestoreMode() {','  return \"session_restore_enabled\";','}',''].join('\\\\n'));",
    "    write('db/migrations/20260416_add_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT;','UPDATE sessions SET restore_mode = \"enabled\";',''].join('\\\\n'));",
    "    write('docs/ROLLBACK.md', ['# Rollback','- Revert the migration if needed.','- Review operator impact before rollback.',''].join('\\\\n'));",
    "    respond('Updated the migration bundle with a compact generic rewrite that still satisfies both repo-local oracles.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/payments/src/migration.ts', ['export function currentRestoreMode() {','  return \"session_restore_enabled:existing-session\";','}',''].join('\\\\n'));",
    "  write('db/migrations/20260416_add_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT DEFAULT \\'existing-session\\';','UPDATE sessions SET restore_mode = \\'existing-session\\' WHERE restore_mode IS NULL;',''].join('\\\\n'));",
    "  write('docs/ROLLBACK.md', ['# Rollback','- Disable the session-restore release flag before rollback.','- ALTER TABLE sessions DROP COLUMN restore_mode;','- Re-run the payments migration smoke check after rollback.',''].join('\\\\n'));",
    "  respond('Updated the migration, rollback, and runtime bundle with concrete operator-reviewable semantics.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'package-script-project-oracle-reviewability') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/web/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  return existingSession;','}',''].join('\\\\n'));",
    "    write('db/migrations/20260416_release_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT;','UPDATE sessions SET restore_mode = \"enabled\";',''].join('\\\\n'));",
    "    write('docs/ROLLBACK.md', ['# Rollback','- Revert the release migration if needed.','- Review operator impact before rollback.',''].join('\\\\n'));",
    "    respond('Updated the release bundle with a compact generic rewrite that still satisfies both repo-local oracles.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/web/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "  write('db/migrations/20260416_release_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT DEFAULT \\'existing-session\\';','UPDATE sessions SET restore_mode = \\'existing-session\\' WHERE restore_mode IS NULL;',''].join('\\\\n'));",
    "  write('docs/ROLLBACK.md', ['# Rollback','- Disable the session-restore release flag before rollback.','- ALTER TABLE sessions DROP COLUMN restore_mode;','- Re-run the workspace session test after rollback.',''].join('\\\\n'));",
    "  respond('Updated the release bundle with concrete runtime, migration, and rollback semantics.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'package-script-repair-stage-guard') {",
    "  if (prompt.includes('Repair context:')) {",
    "    if (candidateId === 'cand-01') {",
    "      write('docs/REPAIR.md', ['# Repair','','- repair marker: added release review note','- Reviewers can inspect the repaired release note.',''].join('\\\\n'));",
    "      respond('Repaired the missing release review note without reopening the staged verification bundle.');",
    "      process.exit(0);",
    "    }",
    "    respond('Repair context was not needed because the release evidence was already complete.');",
    "    process.exit(0);",
    "  }",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/web/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  return existingSession;','}',''].join('\\\\n'));",
    "    write('db/migrations/20260416_release_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT DEFAULT \\'existing-session\\';','UPDATE sessions SET restore_mode = \\'existing-session\\' WHERE restore_mode IS NULL;',''].join('\\\\n'));",
    "    write('docs/ROLLBACK.md', ['# Rollback','- Disable the session-restore release flag before rollback.','- ALTER TABLE sessions DROP COLUMN restore_mode;','- Re-run the workspace session test after rollback.',''].join('\\\\n'));",
    "    respond('Closed the release contract stage only; verification and repair evidence stayed incomplete.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/web/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "  write('db/migrations/20260416_release_session_restore.sql', ['ALTER TABLE sessions ADD COLUMN restore_mode TEXT DEFAULT \\'existing-session\\';','UPDATE sessions SET restore_mode = \\'existing-session\\' WHERE restore_mode IS NULL;',''].join('\\\\n'));",
    "  write('docs/ROLLBACK.md', ['# Rollback','- Disable the session-restore release flag before rollback.','- ALTER TABLE sessions DROP COLUMN restore_mode;','- Re-run the workspace session test after rollback.',''].join('\\\\n'));",
    "  write('docs/VERIFY.md', ['# Verify','- Operators can verify the repaired release bundle end to end.','- Review runtime, migration, rollback, verification, and repair notes together before approval.',''].join('\\\\n'));",
    "  write('docs/REPAIR.md', ['# Repair','','- repair marker: added release review note','- Reviewers can inspect the repaired release note.',''].join('\\\\n'));",
    "  respond('Closed the full staged release bundle and preemptively wrote the review note evidence.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'code-test-contract-coverage') {",
    "  if (candidateId === 'cand-01') {",
    "    write('packages/auth/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "    respond('Updated only the implementation artifact.');",
    "    process.exit(0);",
    "  }",
    "  write('packages/auth/src/session.ts', ['export function restoreSession(request) {','  const existingSession = request.session;','  if (!existingSession) {','    return null;','  }','  return existingSession;','}',''].join('\\\\n'));",
    "  write('packages/auth/test/session-refresh.test.ts', ['import { expect, test } from \"vitest\";','import { restoreSession } from \"../src/session\";','','test(\"restoreSession keeps the signed-in user across refresh\", () => {','  const existingSession = { userId: \"user-123\" };','  const request = { session: existingSession };','  expect(restoreSession(request)).toEqual(existingSession);','});',''].join('\\\\n'));",
    "  respond('Updated the implementation and paired regression test artifact.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'api-schema-reviewability-bias') {",
    "  if (candidateId === 'cand-01') {",
    "    write('services/http/session_handler.py', ['def build_session_response(request):','    return {\"status\": \"ready\"}',''].join('\\\\n'));",
    "    write('api/openapi/session.yaml', ['status: ready','logout_behavior: review-later',''].join('\\\\n'));",
    "    respond('Updated the handler and schema bundle with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('services/http/session_handler.py', ['def build_session_response(request):','    existing_session = request.session','    if existing_session is None:','        return None','    return {\"status\": \"restored\", \"logout_behavior\": \"clears-on-next-load\"}',''].join('\\\\n'));",
    "  write('api/openapi/session.yaml', ['status: restored','logout_behavior: clears-on-next-load',''].join('\\\\n'));",
    "  respond('Updated the handler and schema bundle with concrete API contract markers.');",
    "  process.exit(0);",
    "}",
    "if (scenarioId === 'rust-config-reviewability-bias') {",
    "  if (candidateId === 'cand-01') {",
    "    write('crates/session_core/src/lib.rs', ['pub const SESSION_RESTORE_MODE: &str = \"steady-improvement\";',''].join('\\\\n'));",
    "    write('deploy/session-policy.yaml', ['restore_mode: later','logout_policy: review-later',''].join('\\\\n'));",
    "    respond('Updated the Rust and YAML bundle with a compact generic rewrite.');",
    "    process.exit(0);",
    "  }",
    "  write('crates/session_core/src/lib.rs', ['pub const SESSION_RESTORE_MODE: &str = \"existing-session\";','pub const LOGOUT_POLICY: &str = \"clears-on-next-load\";',''].join('\\\\n'));",
    "  write('deploy/session-policy.yaml', ['restore_mode: existing-session','logout_policy: clears-on-next-load',''].join('\\\\n'));",
    "  respond('Updated the Rust and YAML bundle with concrete runtime markers.');",
    "  process.exit(0);",
    "}",
    "respond('No-op');",
  ].join("\n");
}
