import { z } from "zod";

import { adapterSchema, secondOpinionJudgeTriggerSchema } from "../../config.js";
import { decisionConfidenceSchema } from "../../profile.js";
import {
  clarifyScopeKeyTypeSchema,
  consultationJudgingBasisKindSchema,
  consultationOutcomeTypeSchema,
  consultationPlanReadinessStatusSchema,
  consultationPlanReviewStatusSchema,
  consultationPreflightDecisionSchema,
  consultationResearchPostureSchema,
  consultationValidationPostureSchema,
  consultationVerificationLevelSchema,
} from "../../run.js";
import {
  taskResearchBasisStatusSchema,
  taskResearchConflictHandlingSchema,
  taskSourceKindSchema,
} from "../../task.js";

export const verdictSecondOpinionAgreementSchema = z.enum([
  "agrees-select",
  "agrees-abstain",
  "disagrees-candidate",
  "disagrees-select-vs-abstain",
  "unavailable",
]);

export const verdictArtifactAvailabilitySchema = z.object({
  planReadiness: z.boolean().optional(),
  planReview: z.boolean().optional(),
  planConsensus: z.boolean().optional(),
  preflightReadiness: z.boolean(),
  clarifyFollowUp: z.boolean().default(false),
  researchBrief: z.boolean(),
  failureAnalysis: z.boolean().default(false),
  profileSelection: z.boolean(),
  comparisonReport: z.boolean(),
  winnerSelection: z.boolean(),
  secondOpinionWinnerSelection: z.boolean().default(false),
  crowningRecord: z.boolean(),
});

export const verdictReviewObjectSchema = z.object({
  outcomeType: consultationOutcomeTypeSchema,
  outcomeSummary: z.string().min(1).optional(),
  verificationLevel: consultationVerificationLevelSchema,
  validationPosture: consultationValidationPostureSchema,
  judgingBasisKind: consultationJudgingBasisKindSchema,
  judgingBasisSummary: z.string().min(1).optional(),
  taskSourceKind: taskSourceKindSchema,
  taskSourcePath: z.string().min(1),
  taskArtifactKind: z.string().min(1).optional(),
  targetArtifactPath: z.string().min(1).optional(),
  researchSummary: z.string().min(1).optional(),
  researchConfidence: decisionConfidenceSchema.optional(),
  researchBasisStatus: taskResearchBasisStatusSchema,
  researchConflictHandling: taskResearchConflictHandlingSchema.optional(),
  researchSignalCount: z.number().int().min(0),
  researchSignalFingerprint: z.string().min(1).optional(),
  researchBasisDrift: z.boolean().optional(),
  researchRerunRecommended: z.boolean(),
  researchRerunInputPath: z.string().min(1).optional(),
  researchSourceCount: z.number().int().min(0),
  researchClaimCount: z.number().int().min(0),
  researchVersionNoteCount: z.number().int().min(0),
  researchConflictCount: z.number().int().min(0),
  researchConflictsPresent: z.boolean(),
  taskOriginSourceKind: taskSourceKindSchema.optional(),
  taskOriginSourcePath: z.string().min(1).optional(),
  recommendedCandidateId: z.string().min(1).optional(),
  finalistIds: z.array(z.string().min(1)).default([]),
  strongestEvidence: z.array(z.string().min(1)).default([]),
  weakestEvidence: z.array(z.string().min(1)).default([]),
  judgingCriteria: z.array(z.string().min(1)).min(1).max(5).optional(),
  recommendationSummary: z.string().min(1).optional(),
  recommendationAbsenceReason: z.string().min(1).optional(),
  secondOpinionAdapter: adapterSchema.optional(),
  secondOpinionAgreement: verdictSecondOpinionAgreementSchema.optional(),
  secondOpinionSummary: z.string().min(1).optional(),
  secondOpinionDecision: z.enum(["select", "abstain"]).optional(),
  secondOpinionCandidateId: z.string().min(1).optional(),
  secondOpinionConfidence: decisionConfidenceSchema.optional(),
  secondOpinionTriggerKinds: z.array(secondOpinionJudgeTriggerSchema).default([]),
  secondOpinionTriggerReasons: z.array(z.string().min(1)).default([]),
  manualReviewRecommended: z.boolean().default(false),
  manualCrowningCandidateIds: z.array(z.string().min(1)).default([]),
  manualCrowningReason: z.string().min(1).optional(),
  validationProfileId: z.string().min(1).optional(),
  validationSummary: z.string().min(1).optional(),
  validationSignals: z.array(z.string().min(1)).default([]),
  validationGaps: z.array(z.string().min(1)).default([]),
  planReadinessStatus: consultationPlanReadinessStatusSchema.optional(),
  planReadyForConsult: z.boolean().optional(),
  planReviewStatus: consultationPlanReviewStatusSchema.optional(),
  planStaleBasis: z.boolean().optional(),
  planMissingOracleIds: z.array(z.string().min(1)).optional(),
  planOpenQuestions: z.array(z.string().min(1)).optional(),
  planNextAction: z.string().min(1).optional(),
  planReviewSummary: z.string().min(1).optional(),
  preflightDecision: consultationPreflightDecisionSchema.optional(),
  researchPosture: consultationResearchPostureSchema,
  clarificationQuestion: z.string().min(1).optional(),
  researchQuestion: z.string().min(1).optional(),
  clarifyScopeKeyType: clarifyScopeKeyTypeSchema.optional(),
  clarifyScopeKey: z.string().min(1).optional(),
  clarifyRepeatedCaseCount: z.number().int().min(2).optional(),
  clarifyFollowUpQuestion: z.string().min(1).optional(),
  clarifyMissingResultContract: z.string().min(1).optional(),
  clarifyMissingJudgingBasis: z.string().min(1).optional(),
  artifactAvailability: verdictArtifactAvailabilitySchema,
  candidateStateCounts: z.record(z.string().min(1), z.number().int().min(0)),
});

export type VerdictReviewObject = z.infer<typeof verdictReviewObjectSchema>;
